### ISSUE TITLE
Add cache for Gitbook node modules to speed up book build

### ISSUE THREAD

**Issue by practicalli-john** [practicalli/clojure#427]
Add a simple cache action configuration to the `.github/workflows/publish-website.yaml` workflow

```
      - name: Node Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: cache-${{ hashFiles('**/book.json') }}
```

Reference: https://github.com/actions/cache/blob/main/examples.md#node---npm

Test that the Gitbook plugins and other node_modules are being cached on successive builds
